In [2]:
import numpy as np
import pandas as pd

print("numpy version: {}".format(np.__version__))
print("pandas version: {}".format(pd.__version__))

numpy version: 1.18.1
pandas version: 1.0.3


The following is a simple scenario of data taken from a telemarketing company. The number of successful phone solicitations in 5 days of a particular week by a part-time (PT) and a full-time (FT) employee is recorded in the table below:
<!-- 
|Description|
|-------------------------|-|-|-|-|-|
|X1: Number by PT employee|1|4|2|5|3|
|-------------------------|-|-|-|-|-|
 -->

|Day|X1: Number by PT employee|X2: Number by FT employee|
|---|-------------------------|-------------------------|
|1  |1|9
|2  |4|12
|3  |2|10
|4  |5|8
|5  |3|11

### (a) Find the <mark>sample mean vector</mark> and <mark>sample covariance matrix</mark> of data X. <mark>Interpret</mark> the matrices, and explain the <mark>correlation</mark> between X1 and X2.

In [6]:
X = np.array([[1, 9],
              [4, 12],
              [2, 10],
              [5, 8],
              [3, 11]
             ])

print("X = {}".format(X))

X = [[ 1  9]
 [ 4 12]
 [ 2 10]
 [ 5  8]
 [ 3 11]]


In [21]:
# Find the sample mean vector of data X 
x_bar = np.mean(X, axis=0)
print("x̄={}".format(x_bar.reshape(-1, 1)))

x̄=[[ 3.]
 [10.]]


In [22]:
# Find the sample covariance matrix of data X 
x_C = np.cov(X, rowvar=0)
print("C={}".format(x_C))

C=[[2.5 0. ]
 [0.  2.5]]


In [24]:
x_R = np.corrcoef(X, rowvar=0)
x_R

array([[1., 0.],
       [0., 1.]])

#### Interpretation
#### Correlation

Abby, an administration executive of the company, decided to create three extra variables for her records for the 5 days:<br>
Y1: Total number of successful phone solicitations<br>
Y2: Average number of successful phone solicitations<br>
Y3: Difference in number of successful phone solicitations between FT and PT (FT – PT)

### (b) Express Y1, Y2 and Y3 as linear combinations of X1 and X2.

Let the Total number of successful phone solicitations be $Y_1$.<br>
$Y_1 = X_1 + X_2$

In [29]:
# Total number of successful phone solicitations
y1 = X[:, 0] + X[:, 1]
y1

array([10, 16, 12, 13, 14])

Let the average number of successful phone solicitations be $Y_2$.<br>
$Y_2 = \frac{X_1 + X_2}{2}$

In [30]:
# Average number of successful phone solicitations
y2 = y1/2
y2

array([5. , 8. , 6. , 6.5, 7. ])

Let the difference in number of successful phone solicitations between FT and PT be $Y_3$.<br>
$Y_3 = |X_2 - X_1|$

In [33]:
# Difference in number of successful phone solicitations between FT and PT (FT – PT)
y3 = np.absolute(X[:, 1] - X[:, 0])
y3

array([8, 8, 8, 3, 8])

### (c) Find the sample mean vector and sample covariance matrix of the transformed data Y.

In [43]:
Y = pd.DataFrame({'Y1': y1, 'Y2': y2, 'Y3': y3})
Y

Y1   Y2  Y3
0  10  5.0   8
1  16  8.0   8
2  12  6.0   8
3  13  6.5   3
4  14  7.0   8

In [46]:
# sample mean vector
y_bar = np.mean(Y, axis=0)
y_bar

Y1    13.0
Y2     6.5
Y3     7.0
dtype: float64

In [47]:
# sample covariance matrix
y_C = np.cov(Y, rowvar=0)
y_C

array([[5.  , 2.5 , 0.  ],
       [2.5 , 1.25, 0.  ],
       [0.  , 0.  , 5.  ]])