In [2]:
import numpy as np

print("numpy version: {}".format(np.__version__))

numpy version: 1.18.1


In [5]:
ex7 = np.array([[1, 1, -5], 
                [1, 0, -2], 
                [2, -1, -1]])

ex7

array([[ 1,  1, -5],
       [ 1,  0, -2],
       [ 2, -1, -1]])

In [6]:
np.linalg.det(ex7)

-2.4980018054066007e-16

In [3]:
ex8 = np.array([[1, -4, 2], [1, 2, -2], [1, -1, 0]])
ex8

array([[ 1, -4,  2],
       [ 1,  2, -2],
       [ 1, -1,  0]])

In [4]:
np.linalg.det(ex8)

0.0

In [7]:
ex9 = np.array([[1, 3, 0, -1], 
                [2, -1, 1, 4]])
ex9

array([[ 1,  3,  0, -1],
       [ 2, -1,  1,  4]])

In [8]:
np.linalg.det(ex9)

LinAlgError: Last 2 dimensions of the array must be square