# Practical 2: Systems of Linear Equations

In this practical, we will write code the Gaussian elimination algorithm to solve a system of linear equations with unique solution.

### Task 1

Solve the following system of linear equations

$$\begin{eqnarray}
2x_1 &+& 4x_2 &+& 6x_3 &=& 22 \\
3x_1 &+& 8x_2 &+& 5x_3 &=& 27 \\
-x_1 &+& x_2 &+& 2x_3 &=& 2 \\
\end{eqnarray}$$

given that it has unique solution.

In [1]:
import numpy as np

In [2]:
A = np.array([[2, 4, 6], 
              [3, 8, 5], 
              [-1, 1, 2]], dtype='float')
A

array([[ 2.,  4.,  6.],
       [ 3.,  8.,  5.],
       [-1.,  1.,  2.]])

In [3]:
b = np.array([22, 27, 2])
b

array([22, 27,  2])

In [4]:
Ab = np.hstack([A, b.reshape(-1, 1)])
Ab

array([[ 2.,  4.,  6., 22.],
       [ 3.,  8.,  5., 27.],
       [-1.,  1.,  2.,  2.]])

Find the number of linear equations and store in n.

In [5]:
n = len(b)

The algorithm below is used to convert the augmented matrix to row echelon form.<br>
Illustrated below is the algorithm applied to this example:
$$
\begin{bmatrix}
\begin{array}{c c c|c}
  2 & 4 & 6 & 22 \\ 
  3 & 8 & 5 & 27 \\
  -1 & 1 & 2 & 2
 \end{array}
\end{bmatrix}
$$


$$
\xrightarrow[R_{3}-(-\frac{1}{2}R_{1})]{R_{2}-\frac{3}{2}R_{1}}
\begin{bmatrix}
\begin{array}{c c c|c}
  2 & 4 & 6 & 22 \\ 
  0 & 2 & -4 & -6 \\
  0 & 3 & 5 & 13
 \end{array} 
\end{bmatrix}
$$


$$
\xrightarrow[]{R_{3}-\frac{3}{2}R_{2}}
\begin{bmatrix}
\begin{array}{c c c|c}
  2 & 4 & 6 & 22 \\ 
  0 & 2 & -4 & -6 \\
  0 & 0 & 11 & 22
 \end{array} 
\end{bmatrix}
$$

In [6]:
#Converts augmented matrix to row echelon form
for i in range(n):
    a = Ab[i]

    for j in range(i + 1, n):
        b = Ab[j]
        m = b[i] / a[i]
        Ab[j] = b - m * a

In [7]:
Ab

array([[ 2.,  4.,  6., 22.],
       [ 0.,  2., -4., -6.],
       [ 0.,  0., 11., 22.]])

The algorithm below is used to convert row echelon form to reduced row echelon form (only one '1' in each row on the left side of the augmented matrix).<br>
Illustrated below is the algorithm applied to this example:
$$
\begin{bmatrix}
\begin{array}{c c c|c}
  2 & 4 & 6 & 22 \\ 
  0 & 2 & -4 & -6 \\
  0 & 0 & 11 & 22
 \end{array}
\end{bmatrix}$$

$$
\xrightarrow[]{\frac{1}{11}R_{3}}
\begin{bmatrix}
\begin{array}{c c c|c}
  2 & 4 & 6 & 22 \\ 
  0 & 2 & -4 & -6 \\
  0 & 0 & 1 & 2
 \end{array} 
\end{bmatrix}
$$

$$
\xrightarrow[-\frac{1}{6}R_{1} + R_{3}]{-(\frac{1}{-4})R_{2} + R_{3}}
\begin{bmatrix}
\begin{array}{c c c|c}
  -\frac{1}{3} & -\frac{2}{3} & 0 & -\frac{5}{3} \\ 
  0 & \frac{1}{2} & 0 & \frac{1}{2} \\
  0 & 0 & 1 & 2
 \end{array} 
\end{bmatrix}
$$

$$
\xrightarrow[]{\frac{1}{0.5}R_{2}}
\begin{bmatrix}
\begin{array}{c c c|c}
  -\frac{1}{3} & -\frac{2}{3} & 0 & -\frac{5}{3} \\ 
  0 & 1 & 0 & 1 \\
  0 & 0 & 1 & 2
 \end{array} 
\end{bmatrix}
$$

$$
\xrightarrow[]{-\frac{1}{-\frac{2}{3}}R_{1} + R_{2}}
\begin{bmatrix}
\begin{array}{c c c|c}
  -\frac{1}{2} & 0 & 0 & -\frac{3}{2} \\ 
  0 & 1 & 0 & 1 \\
  0 & 0 & 1 & 2
 \end{array} 
\end{bmatrix}
$$

$$
\xrightarrow[]{\frac{1}{-0.5}R_{1}}
\begin{bmatrix}
\begin{array}{c c c|c}
  1 & 0 & 0 & 3 \\ 
  0 & 1 & 0 & 1 \\
  0 & 0 & 1 & 2
 \end{array} 
\end{bmatrix}
$$

In [8]:
#Converts row echelon form to reduced row echelon form
for i in range(n - 1, -1, -1):
    Ab[i] = Ab[i] / Ab[i, i]
    a = Ab[i]

    for j in range(i - 1, -1, -1):
        b = Ab[j]
        m = a[i] / b[i]
        Ab[j] = a - m * b
Ab

array([[ 1., -0., -0.,  3.],
       [ 0.,  1.,  0.,  1.],
       [ 0.,  0.,  1.,  2.]])

We can now have the answers<br>
$$\begin{eqnarray}
x_1 &=& 3 \\
x_2 &=& 1 \\
x_3 &=& 2 \\
\end{eqnarray}$$

In [9]:
x = Ab[:, n]
x

array([3., 1., 2.])

### Task 2

Modify the code from task 1 and use it to solve the following system of linear equations

$$\begin{eqnarray}
&       &2x_2 &+&  3x_3 &=&  7 \\
3x_1 &+& 6x_2 &-& 12x_3 &=& -3 \\
5x_1 &-& 2x_2 &+&  2x_3 &=& -7 \\
\end{eqnarray}$$

given that it has unique solution.<br>
Hint: You will need to make an improvement to the section of the code that converts the augmented matrix to row echelon form.

In [10]:
A = np.array([[0, 2, 3], [3, 6, -12], [5, -2, 2]], dtype='float')
b = np.array([7, -3, -7])
Ab = np.hstack([A, b.reshape(-1, 1)])

n = len(b)

In [11]:
#Converts augmented matrix to row echelon form. Modify this part.
for i in range(n):
    a = Ab[i]

    for j in range(i + 1, n):
        b = Ab[j]
        m = b[i] / a[i]
        Ab[j] = b - m * a

C:\Users\Silviana\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: RuntimeWarning: divide by zero encountered in double_scalars
  import sys
C:\Users\Silviana\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: invalid value encountered in multiply
  
C:\Users\Silviana\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: RuntimeWarning: invalid value encountered in double_scalars
  import sys


In [12]:
#Converts row echelon form to reduced row echelon form.
for i in range(n - 1, -1, -1):
    Ab[i] = Ab[i] / Ab[i, i]
    a = Ab[i]

    for j in range(i - 1, -1, -1):
        b = Ab[j]
        m = a[i] / b[i]
        Ab[j] = a - m * b

x = Ab[:, n]
x

array([nan, nan, nan])

### Task 3

Modify the code from task 2 and use it to solve the following system of linear equations

$$\begin{eqnarray}
x_1 &-& x_2 &     & &=& 3 \\
x_1 &      & &-& x_3 &=& -2 \\
-6x_1 &+& 2x_2 &+& 3x_3 &=& 0 \\
\end{eqnarray}$$

given that it has unique solution.<br>
Hint: You will need to make an improvement to the section of the code that converts row echelon form to reduced row echelon form.

### Task 4

Given a system of 10 linear equations (below) that has a unique solution, compare the time taken to solve the system of linear equations using your code from task 3 with numpy.linalg.solve.

$$
\begin{align*}
3x_{1} + 5x_{2} + 4x_{3} + 3x_{4} - 8x_{5} - 8x_{6} - 6x_{7} - 6x_{8} - 6x_{9} - 7x_{10} &= -148 \\
6x_{1} + 9x_{2} + 6x_{3} - 3x_{4} + 6x_{5} - 8x_{6} - 7x_{7} + 5x_{8} - 6x_{9} - 3x_{10} &= 29 \\
8x_{1} + 3x_{2} - 7x_{3} + x_{4} - 4x_{5} + 3x_{6} - 4x_{7} - 2x_{8} - 6x_{9} + 4x_{10} &= 84 \\
4x_{1} - 4x_{2} + 5x_{3} + 7x_{4} - 5x_{5} - 8x_{6} + 5x_{7} + 0x_{8} + 8x_{9} + 8x_{10} &= -88 \\
9x_{1} + 8x_{2} + 10x_{3} - 6x_{4} - 3x_{5} - 3x_{6} + 5x_{7} - 8x_{8} - 2x_{9} - 7x_{10} &= -208 \\
-5x_{1} + x_{2} + 8x_{3} - 3x_{4} + 4x_{5} - 4x_{6} - x_{7} + 6x_{8} - 9x_{9} + x_{10} &= -64 \\
-8x_{1} - 6x_{2} + 6x_{3} + 0x_{4} + 10x_{5} - 8x_{6} + 4x_{7} + 2x_{8} - 4x_{9} - x_{10} &= -75 \\
x_{1} + 2x_{2} + x_{3} + 8x_{4} - 4x_{5} + 5x_{6} - 10x_{7} + 7x_{8} + 0x_{9} - 2x_{10} &= 124 \\
7x_{1} + 4x_{2} - 6x_{3} - 7x_{4} - 7x_{5} - 10x_{6} - 7x_{7} - 8x_{8} + 8x_{9} + 3x_{10} &= -59 \\
-2x_{1} - 7x_{2} + 0x_{3} - 3x_{4} + 5x_{5} - 8x_{6} - 6x_{7} - 9x_{8} - 5x_{9} - 3x_{10} &= -62 \\
\end{align*}
$$


In [13]:
import timeit

In [14]:
#Find the time taken to solve the system of linear equations using Guassian elimination
Gaussian = '''
import numpy as np
A = np.array([[3, 5, 4, 3, -8, -8, -6, -6, -6, -7], [6, 9, 6, -3, 6, -8, -7, 5, -6, -3], [8, 3, -7, 1, -4, 3, -4, -2, -6, 4], [4, -4, 5, 7, -5, -8, 5, 0, 8, 8], [9, 8, 10, -6, -3, -3, 5, -8, -2, -7], [-5, 1, 8, -3, 4, -4, -1, 6, -9, 1], [-8, -6, 6, 0, 10, -8, 4, 2, -4, -1], [1, 2, 1, 8, -4, 5, -10, 7, 0, -2], [7, 4, -6, -7, -10, -10, -7, -8, 8, 3], [-2, -7, 0, -3, 5, -8, -6, -9, -5, -3]], dtype='float')
b = np.array([-148, 29, 84, -88, -208, -64, -75, 124, -59, -62])
Ab = np.hstack([A, b.reshape(-1, 1)])
n = len(b)

# Put your code from Task 3 here



print(x)
'''

print("Time taken is ", timeit.timeit(stmt = Gaussian, number = 10000))

NameError: name 'x' is not defined

In [ ]:
#Find the time taken to solve the system of linear equations using numpy.linalg.solve
Auto = '''
A = np.array([[3, 5, 4, 3, -8, -8, -6, -6, -6, -7], [6, 9, 6, -3, 6, -8, -7, 5, -6, -3], [8, 3, -7, 1, -4, 3, -4, -2, -6, 4], [4, -4, 5, 7, -5, -8, 5, 0, 8, 8], [9, 8, 10, -6, -3, -3, 5, -8, -2, -7], [-5, 1, 8, -3, 4, -4, -1, 6, -9, 1], [-8, -6, 6, 0, 10, -8, 4, 2, -4, -1], [1, 2, 1, 8, -4, 5, -10, 7, 0, -2], [7, 4, -6, -7, -10, -10, -7, -8, 8, 3], [-2, -7, 0, -3, 5, -8, -6, -9, -5, -3]], dtype='float')
b = np.array([-148, 29, 84, -88, -208, -64, -75, 124, -59, -62])
Ab = np.hstack([A, b.reshape(-1, 1)])
n = len(b)
print(np.linalg.solve(A,b))
'''

print(timeit.timeit(stmt = Auto, number = 10000))

You will notice that numpy.linalg.solve takes a shorter time to solve the system of linear equations as it uses the LAPACK routine. However, numpy.linalg.solve can only solve a system of linear equations with a unique solution.

### Task 5
If we do not know the number of solutions our system of linear equations has, we can use sympy.linsolve.

For example, we can use sympy.linsolve to solve the following system of linear equations which has many solutions:
\begin{eqnarray}
x_1 + x_2 - 5x_3 = 3 \\
x_1 - 2x_3 = 1 \\
2x_1 - x_2 - x_3 = 0
\end{eqnarray}

In [ ]:
import sympy as sp

In [ ]:
sp.init_printing()

In [ ]:
x1, x2, x3 = sp.symbols('x1 x2 x3')

In [ ]:
A5 = sp.Matrix([[1,1,-5], [1, 0, -2], [2,-1,-1]])

In [ ]:
b5 = sp.Matrix([[3], [1], [0]])

In [ ]:
sp.linsolve((A5, b5), x1, x2, x3)