In [1]:
import numpy as np

print("numpy version: {}".format(np.__version__))

numpy version: 1.18.1


In [2]:
two_a = np.array([[3, -1],
                  [-6, 2]])
two_a

array([[ 3, -1],
       [-6,  2]])

In [3]:
np.linalg.det(two_a)

0.0

---

In [56]:
# Converts augmented matrix to row echelon form
def row_echelon(matrix, n):
    for i in range(n):
        a = matrix[i]

        for j in range(i + 1, n):
            b = matrix[j]
            m = b[i] / a[i]
            matrix[j] = b - m * a
        print(matrix)
    return matrix

In [5]:
# Converts row echelon form to reduced row echelon form
def reduced_re(matrix, n):
    row_echelon(matrix, n)
    for i in range(n - 1, -1, -1):
        matrix[i] = matrix[i] / matrix[i, i]
        a = matrix[i]

        for j in range(i - 1, -1, -1):
            b = matrix[j]
            m = a[i] / b[i]
            matrix[j] = a - m * b
    return matrix

In [6]:
# final matrix
# def rre_matrix

---

In [7]:
two_c_lhs = np.array([[3, -2, 1],
                  [1, -1, 3],
                  [-1, 1, 1]
                 ], dtype="float")
np.linalg.det(two_c_lhs)

-4.000000000000001

In [8]:
two_c_rhs = np.array([-2, 5, -1])

In [9]:
two_c = np.hstack([two_c_lhs, two_c_rhs.reshape(-1, 1)])
two_c

array([[ 3., -2.,  1., -2.],
       [ 1., -1.,  3.,  5.],
       [-1.,  1.,  1., -1.]])

In [10]:
n2c = len(two_c_rhs)
# twoc_re= row_echelon(two_c, n2c)
# twoc_rre = reduced_re(two_c, n2c)
# twoc_rre = reduced_re(twoc_re, n2c)
reduced_re(two_c, n2c)

array([[ 1.,  0.,  0., -7.],
       [ 0.,  1.,  0., -9.],
       [ 0.,  0.,  1.,  1.]])

In [11]:
two_c

array([[ 1.,  0.,  0., -7.],
       [ 0.,  1.,  0., -9.],
       [ 0.,  0.,  1.,  1.]])

---

In [12]:
two_d_lhs = np.array([[1, 2, -4],
                      [2, -1, 2],
                      [1, 1, -2]], dtype="float")

np.linalg.det(two_d_lhs)

5.551115123125802e-16

In [13]:
two_d_rhs = np.array([10, 5, 7])
n2d = len(two_d_rhs)

In [14]:
two_d = np.hstack([two_d_lhs, two_d_rhs.reshape(-1, 1)])
two_d

array([[ 1.,  2., -4., 10.],
       [ 2., -1.,  2.,  5.],
       [ 1.,  1., -2.,  7.]])

In [15]:
# reduced_re(two_d, n2d)

---

In [16]:
two_h_lhs = np.array([[3, 1, 1, 1],
                      [5, -1, 1, -1]
                     ], dtype="float")

In [17]:
two_h_rhs = np.array([0, 0])
n2h = len(two_h_rhs)

In [18]:
two_h = np.hstack([two_h_lhs, two_h_rhs.reshape(-1, 1)])
two_h

array([[ 3.,  1.,  1.,  1.,  0.],
       [ 5., -1.,  1., -1.,  0.]])

In [19]:
row_echelon(two_h, n2h)

array([[ 3.        ,  1.        ,  1.        ,  1.        ,  0.        ],
       [ 0.        , -2.66666667, -0.66666667, -2.66666667,  0.        ]])

In [20]:
reduced_re(two_h, n2h)

array([[ 1.  , -0.  ,  0.25, -0.  ,  0.  ],
       [-0.  ,  1.  ,  0.25,  1.  , -0.  ]])

In [21]:
# reduced_re(two_h, n2h)

---

In [22]:
sev_lhs = np.array([[1, -1, -1],
                    [180, 230, 160],
                    [110, 120, 90]
                   ], dtype="float")
np.linalg.det(sev_lhs)

3800.0000000000014

In [23]:
sev_rhs = np.array([0, 2660, 1520])
n7 = len(sev_rhs)

In [24]:
sev = np.hstack([sev_lhs, sev_rhs.reshape(-1, 1)])
sev

array([[ 1.00e+00, -1.00e+00, -1.00e+00,  0.00e+00],
       [ 1.80e+02,  2.30e+02,  1.60e+02,  2.66e+03],
       [ 1.10e+02,  1.20e+02,  9.00e+01,  1.52e+03]])

In [25]:
np.around(reduced_re(sev, n7))

array([[ 1.,  0.,  0.,  7.],
       [-0.,  1., -0.,  4.],
       [ 0., -0.,  1.,  3.]])

---

In [40]:
tut4_3b_lhs = np.array([[0, 0, 6],
                    [4, 8, 3],
                    [1, 2, 4]
                   ])
np.linalg.det(tut4_3b_lhs)

0.0

In [41]:
tut4_3b_rhs = np.array([0, 0, 0])

In [42]:
tut4_3b = np.hstack([tut4_3b_lhs, tut4_3b_rhs.reshape(-1, 1)])

In [43]:
np.around(reduced_re(tut4_3b, len(tut4_3b_rhs)))

C:\Users\Silviana\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in long_scalars
  
C:\Users\Silviana\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: RuntimeWarning: invalid value encountered in multiply
  if __name__ == '__main__':
C:\Users\Silviana\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in true_divide
  """
C:\Users\Silviana\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in true_divide
  """


array([[-2147483648, -2147483648, -2147483648, -2147483648],
       [-2147483648, -2147483648, -2147483648, -2147483648],
       [-2147483648, -2147483648, -2147483648, -2147483648]])

In [57]:
test_lhs = np.array([[0, 2],
                    [0,2]
                   ])
np.linalg.det(test_lhs)

0.0

In [58]:
test_rhs = np.array([0, 0])

In [59]:
test = np.hstack([test_lhs, test_rhs.reshape(-1, 1)])
test

array([[0, 2, 0],
       [0, 2, 0]])

In [60]:
np.around(reduced_re(test, len(test_rhs)))

[[          0           2           0]
 [-2147483648 -2147483648 -2147483648]]
[[          0           2           0]
 [-2147483648 -2147483648 -2147483648]]


C:\Users\Silviana\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: invalid value encountered in long_scalars
  


array([[1, 0, 1],
       [1, 1, 1]])