# Practical 4: Eigenvalues and Eigenvectors

### Eigenvalues & Eigenvectors of a Square Matrix

In [1]:
import numpy as np
# Define square matrix A
A = np.array([[2,0,1],[-1,4,-1],[-1,2,0]])
print(A)
eigvals, eigvecs = np.linalg.eig(A)
print("Eigenvalues are: ", eigvals)
print("Eigenvectors are: ", eigvecs)

[[ 2  0  1]
 [-1  4 -1]
 [-1  2  0]]
Eigenvalues are:  [3. 2. 1.]
Eigenvectors are:  [[ 4.08248290e-01  8.94427191e-01 -7.07106781e-01]
 [ 8.16496581e-01  4.47213595e-01 -3.77662374e-16]
 [ 4.08248290e-01  1.28932541e-15  7.07106781e-01]]


So the eigenvalues of A are: 3, 2, and 1
Notice that the corresponding eigenvectors are given in columns and are 
normalized to unit length.

In [2]:
# The first eigenvalue is 3
# Its corresponding eigenvector is in column 1 of eigvecs
print("First eigenvalue is: ", eigvals[0])# subject to rounding errors
print("Corresponding eigenvector is: ", eigvecs[:,0])
print("Its magnitude is: ", np.linalg.norm(eigvecs[:,0])) # subject to rounding error


First eigenvalue is:  2.9999999999999987
Corresponding eigenvector is:  [0.40824829 0.81649658 0.40824829]
Its magnitude is:  0.9999999999999999


To check whether the first vector and first value are indeed the eigenvector and eigenvalue
of A, we do the following:

In [3]:
# Find Av
B = np.dot(A, eigvecs[:,0])
print("Av is: ", B)

# Find lambda*v
C = eigvals[0]* eigvecs[:,0]
print("lambda*v is: ", C)


Av is:  [1.22474487 2.44948974 1.22474487]
lambda*v is:  [1.22474487 2.44948974 1.22474487]


Notice that the two answers are the same, confirming that the first vector is an eigenvector
corresponding to the first eigenvalue. 

### Task 1

Some properties of eigenvalues include:<br> 
•	The sum of eigenvalues of a matrix equals its trace.<br>
•	The product of eigenvalues equals its determinant.<br><br>
Verify the properties above using the matrix $\mathbf{A}=\begin{bmatrix}2 & 1 & 2 \\ 2 & 2 & -2 \\ 3 & 1 & 1 \end{bmatrix}$

In [4]:
A = np.array([[2,1,2],[2,2,-2],[3,1,1]])

In [5]:
evalues, evectors = np.linalg.eig(A)

In [6]:
evalues #Sum of eigenvalues = 5

array([-1.,  4.,  2.])

In [7]:
# Product of eigenvalues = -8

In [8]:
np.linalg.det(A)

-8.000000000000002

### Task 2

**Symmetric Matrix**: The eigenvalues of a symmetrical matrix are always real and the eigenvectors are always orthogonal. Verify this in Python for the matrix A below.<br>
$$\mathbf{A}=\begin{bmatrix}1 & -1 & 0 \\ -1 & 2 & -1 \\ 0 & -1 & 1 \end{bmatrix}$$

In [9]:
A = np.array([[1,-1,0],[-1,2,-1],[0,-1,1]])

In [10]:
evalues, evectors = np.linalg.eig(A)

In [11]:
evalues

array([ 3.00000000e+00,  1.00000000e+00, -3.36770206e-17])

In [12]:
v1 = evectors[ : , 0]
v2 = evectors[ : , 1]
v3 = evectors[ : , 2]

In [13]:
v1

array([-0.40824829,  0.81649658, -0.40824829])

In [14]:
v2

array([-7.07106781e-01,  2.61239546e-16,  7.07106781e-01])

In [15]:
v3

array([0.57735027, 0.57735027, 0.57735027])

In [17]:
v1.dot(v2)

-2.1908073116703266e-16

In [18]:
v2.dot(v3)

1.8673472812034283e-16

In [19]:
v1.dot(v3)

2.7755575615628914e-16