In [1]:
import numpy as np
import pandas as pd

print("numpy version: {}".format(np.__version__))
print("pandas version: {}".format(pd.__version__))

numpy version: 1.18.1
pandas version: 1.0.3


In [2]:
A = np.array([[2, 0, 1],
              [-1, 4, -1],
              [-1, 2, 0]
             ])
A

array([[ 2,  0,  1],
       [-1,  4, -1],
       [-1,  2,  0]])

In [3]:
np.linalg.eig(A)

(array([3., 2., 1.]),
 array([[ 4.08248290e-01,  8.94427191e-01, -7.07106781e-01],
        [ 8.16496581e-01,  4.47213595e-01, -3.77662374e-16],
        [ 4.08248290e-01,  1.28932541e-15,  7.07106781e-01]]))

In [4]:
np.linalg.det(A)

6.0

In [9]:
three_b = np.array([[0, 0, 6],
                    [4, 8, 3],
                    [1, 2, 4]
                   ])
three_b

array([[0, 0, 6],
       [4, 8, 3],
       [1, 2, 4]])

In [10]:
np.linalg.eig(three_b)

(array([1.00000000e+01, 1.26103555e-15, 2.00000000e+00]),
 array([[ 2.04006120e-01,  8.94427191e-01,  7.44208408e-01],
        [ 9.18027541e-01, -4.47213595e-01, -6.20173673e-01],
        [ 3.40010200e-01,  1.08095870e-16,  2.48069469e-01]]))