In [1]:
import numpy as np
import pandas as pd

# Chapter 1 

In [2]:
# making an array (vector)
v = np.array([[1],
              [4]])
vdimension = v.shape

In [3]:
# matrix addition and subtraction
A = np.array([[5,8],
              [6,9]])
B = np.array([[3,2],
              [4,-1]])
C = A + B
D = A - B

In [4]:
# multiplication
# scalar
E = A * 2

# matrix-vector or matrix-matrix
F = np.dot(A, v)
G = np.dot(A, B)

In [5]:
# transpose
H = A.T

# trace
traceA = np.trace(A)

# determinant
detA = np.linalg.det(A)

#inverse
invA = np.linalg.inv(A)

In [6]:
# Identity matrix
I3 = np.eye(3)

# Diagonal matrix
J = np.diag((1, 5, 1))

# Ones
K = np.ones((1, 3))

In [48]:
# Norm of vector
v2 = np.array([[1], [0], [2], [2], [3]])
norm_v2 = np.linalg.norm(v2)
norm_v2

# Chapter 2 

In [8]:
A = np.array([[2, 4, 6], [3, 8, 5], [-1, 1, 2]], dtype='float')
b = np.array([22, 27, 2])

Ab = np.hstack([A, b.reshape(-1, 1)])

n = len(b)

In [9]:
# Converts augmented matrix to row echelon form
for i in range(n):
    a = Ab[i]

    for j in range(i + 1, n):
        b = Ab[j]
        m = b[i] / a[i]
        Ab[j] = b - m * a

In [10]:
# Converts row echelon form to reduced row echelon form
for i in range(n - 1, -1, -1):
    Ab[i] = Ab[i] / Ab[i, i]
    a = Ab[i]

    for j in range(i - 1, -1, -1):
        b = Ab[j]
        m = a[i] / b[i]
        Ab[j] = a - m * b

In [11]:
x = Ab[:, n]

In [12]:
A = np.array([[3, 5, 4, 3, -8, -8, -6, -6, -6, -7],
              [6, 9, 6, -3, 6, -8, -7, 5, -6, -3],
              [8, 3, -7, 1, -4, 3, -4, -2, -6, 4],
              [4, -4, 5, 7, -5, -8, 5, 0, 8, 8],
              [9, 8, 10, -6, -3, -3, 5, -8, -2, -7],
              [-5, 1, 8, -3, 4, -4, -1, 6, -9, 1],
              [-8, -6, 6, 0, 10, -8, 4, 2, -4, -1],
              [1, 2, 1, 8, -4, 5, -10, 7, 0, -2],
              [7, 4, -6, -7, -10, -10, -7, -8, 8, 3],
              [-2, -7, 0, -3, 5, -8, -6, -9, -5, -3]], dtype='float')
b = np.array([-148, 29, 84, -88, -208, -64, -75, 124, -59, -62])
# numpy.linalg.solve is faster but it can only solve a system of linear equations with a unique solution.
np.linalg.solve(A,b)

array([ 3.,  2., -8.,  4.,  9.,  6., -7.,  5.,  3.,  3.])

In [13]:
# If we do not know the number of solutions our system of linear equations has, we can use sympy.linsolve.
import sympy as sp

In [14]:
sp.init_printing()

In [15]:
x1, x2, x3 = sp.symbols('x1 x2 x3')

In [16]:
A5 = sp.Matrix([[1,1,-5], [1, 0, -2], [2,-1,-1]])
A5

⎡1  1   -5⎤
⎢         ⎥
⎢1  0   -2⎥
⎢         ⎥
⎣2  -1  -1⎦

In [17]:
b5 = sp.Matrix([[3], [1], [0]])
b5

⎡3⎤
⎢ ⎥
⎢1⎥
⎢ ⎥
⎣0⎦

In [18]:
sp.linsolve((A5, b5), x1, x2, x3)

# Chapter 3 

In [19]:
data = np.array([[16.44, 12.43, 11.23],
                   [ 7.19,  2.7 ,  3.92],
                   [ 9.92,  1.35,  9.75],
                   [ 4.24,  5.78,  7.78],
                   [11.2 ,  5.05, 10.67],
                   [14.25,  5.78,  9.88],
                   [13.5 , 10.98, 10.6 ],
                   [13.32, 14.27,  9.45],
                   [12.68,  7.61, 10.23],
                   [ 7.51,  5.8 ,  8.13],
                   [ 9.9 ,  3.63,  9.13],
                   [10.25,  5.07, 10.17],
                   [11.11,  6.15,  7.61],
                   [12.17, 14.26, 14.39],
                   [10.24,  2.59,  6.09],
                   [10.18,  6.05, 12.14],
                   [ 8.88,  2.7 , 12.23],
                   [12.34,  7.73, 11.68],
                   [ 8.51, 14.02, 12.01],
                   [12.95,  8.24,  7.18],
                   [16.93, 13.37, 17.59],
                   [14.7 , 10.78, 14.58],
                   [10.32,  5.16, 17.  ],
                   [ 8.98,  4.49,  4.26],
                   [ 9.7 , 11.59,  6.83],
                   [12.72,  8.63,  5.59],
                   [ 9.49,  2.16,  6.23],
                   [ 8.22,  7.95,  6.72],
                   [13.7 , 11.22,  4.91],
                   [ 8.21,  9.85,  8.17],
                   [15.86, 11.42, 13.06],
                   [ 9.18,  9.18,  9.49],
                   [12.49,  4.67, 11.94],
                   [17.32,  6.86,  4.44]])

In [20]:
# Find sample mean vector. axis=0 indicates each column in the data matrix is a variable.
x_bar = np.mean(data, axis=0)

In [21]:
# Find sample covariance matrix. rowvar=0 indicates each column in the data matrix is a variable. 
C = np.cov(data, rowvar=0)

# Find generalised sample variance
np.linalg.det(C)

# Find total sample variance
np.trace(C)

In [22]:
# Find sample correlation matrix
R = np.corrcoef(data, rowvar=0)

In [23]:
# If y1 = x1 + x2
y1 = data[:, 0] + data[:, 1]

# Chapter 4 

In [24]:
# Define square matrix A
A = np.array([[2,0,1],[-1,4,-1],[-1,2,0]])

# find the eigenvalues and the corresponding eigenvectors
eigvals, eigvecs = np.linalg.eig(A)

---

# Q1

In [25]:
q1 = np.array([[],
               []
              ])

# Q2

In [ ]:
q2 = np.array([[],
               []
              ])

# Q3

In [ ]:
q3 = np.array([[],
               []
              ])

# Q4 

In [29]:
q4 = np.array([[31, 37],
               [38, 29],
               [42, 78]
              ])

In [36]:
xbar4 = np.mean(q4, axis=0)

In [37]:
c4 = np.cov(q4, rowvar=0)

In [38]:
r4 = np.corrcoef(q4, rowvar=0)


In [56]:
eigvals4, eigvecs4 = np.linalg.eig(c4)
eigvals4, eigvecs4

(array([ 16.61322615, 705.38677385]),
 array([[-0.98950112, -0.14452517],
        [ 0.14452517, -0.98950112]]))

In [54]:
eigvecs4[:, 0]

array([-0.98950112,  0.14452517])

In [55]:
eigvecs4[:, 1]

array([-0.14452517, -0.98950112])