In [2]:
import numpy as np
import pandas as pd

print("numpy version: {}".format(np.__version__))
print("pandas version: {}".format(pd.__version__))

numpy version: 1.18.1
pandas version: 1.0.3


In [4]:
C = np.array([[5, 2],
              [2, 2]
             ])

np.linalg.eig(C)

(array([6., 1.]),
 array([[ 0.89442719, -0.4472136 ],
        [ 0.4472136 ,  0.89442719]]))

In [5]:
A = np.array([[1, 2],
              [0, 3]
             ])

np.linalg.eig(A)

(array([1., 3.]),
 array([[1.        , 0.70710678],
        [0.        , 0.70710678]]))

In [6]:
V = np.array([[1, 1],
              [0, 1]
             ])
V

array([[1, 1],
       [0, 1]])

In [7]:
V_inv = np.linalg.inv(V)

V_inv

array([[ 1., -1.],
       [ 0.,  1.]])

In [8]:
eigvals = np.array([[1, 0],
                    [0, 3]
                   ])

eigvals

array([[1, 0],
       [0, 3]])

In [17]:
V.dot(eigvals).dot(eigvals).dot(eigvals).dot(eigvals).dot(V_inv)

array([[ 1., 80.],
       [ 0., 81.]])

In [37]:
q7 = np.array([[2, 2, -1],
               [1, 3, -1],
               [-1, -2, 2]
              ], dtype="float")

q7

array([[ 2.,  2., -1.],
       [ 1.,  3., -1.],
       [-1., -2.,  2.]])

In [38]:
q7_eig = np.linalg.eig(q7)
q7_eig

(array([1., 5., 1.]),
 array([[-0.90453403,  0.57735027, -0.04093652],
        [ 0.30151134,  0.57735027,  0.46313831],
        [-0.30151134, -0.57735027,  0.88534011]]))

In [39]:
q7_eigval = np.diag(q7_eig[0])
q7_eigval 

array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 1.]])

In [40]:
q7_eigvec = q7_eig[1]
q7_eigvec

array([[-0.90453403,  0.57735027, -0.04093652],
       [ 0.30151134,  0.57735027,  0.46313831],
       [-0.30151134, -0.57735027,  0.88534011]])

In [41]:
q7_eigvec_inv = np.linalg.inv(q7_eigvec)
q7_eigvec_inv

array([[-8.29156198e-01,  5.19209252e-01, -3.09946946e-01],
       [ 4.33012702e-01,  8.66025404e-01, -4.33012702e-01],
       [-1.37219230e-17,  7.41576569e-01,  7.41576569e-01]])

In [42]:
A = q7_eigvec.dot(q7_eigval).dot(q7_eigvec_inv)
A

array([[ 2.,  2., -1.],
       [ 1.,  3., -1.],
       [-1., -2.,  2.]])