# Practical 1: Vectors & Matrices


Many machine learning algorithms make use of matrices to store and process data. 
For example, a deep learning algorithm makes use of matrices to store inputs such as 
images, tweets, or text to solve problems. An artificial neural network makes use of 
matrices to store information such as weights during training. A familiarity with 
matrices and vectors is hence important.

In this practical we will learn some of the fundamentals of matrices and vectors.

A **vector** can be represented as a list in Python.
For example:

In [1]:
v = [ 1, 4, 2]
print(v)

[1, 4, 2]


A **matrix** is a 2D array which stores numbers. 
Alternatively, a matrix can also be thought of as 
a list of vectors.

An example:

In [2]:
A = [[1,4,2],[0,6,3],[3,5,6]]
print(A)

[[1, 4, 2], [0, 6, 3], [3, 5, 6]]


An alternative way to work with vectors and matrices is
to use the **NumPy** module in Python.

In [3]:
import numpy as np
v = np.array([[1],
               [4],
               [2]])
print(v)
A = np.array([[1,4, 2], [0, 6, 3],[3, 5, 6]])
print(A)

[[1]
 [4]
 [2]]
[[1 4 2]
 [0 6 3]
 [3 5 6]]


We can check the order of **A** and **v** as follows:

In [4]:
print("A if of dimension: ", A.shape)
print("v is of dimension: ", v.shape)

A if of dimension:  (3, 3)
v is of dimension:  (3, 1)


There are a lot of matrix operations which we can make use
of in **NumPy**. Some examples are given below.

In [5]:
# Matrix Addition
A = np.array([[5,8],[6,9]])
print(A)
B = np.array([[3,2],[4,-1]])
print(B)
C = A+B
print(C)

[[5 8]
 [6 9]]
[[ 3  2]
 [ 4 -1]]
[[ 8 10]
 [10  8]]


In [6]:
# Matrix Subtraction
D = A - B
print(D)

[[ 2  6]
 [ 2 10]]


In [7]:
# Matrix-Scalar Multiplication
A = np.array([[5,8],[6,9]])
print(A)
b = 2
E = A*2
print(E)

[[5 8]
 [6 9]]
[[10 16]
 [12 18]]


In [8]:
# Matrix-Vector Multiplication
A = np.array([[5,8],[6,9]])
print(A)
v = np.array([[1],[4]])
print(v)
w = np.dot(A,v)
print(w)

[[5 8]
 [6 9]]
[[1]
 [4]]
[[37]
 [42]]


In [9]:
# Matrix-Matrix Multiplication
A = np.array([[5,8],[6,9]])
print(A)
B = np.array([[3,2],[4,-1]])
print(B)
C = np.dot(A,B)
print(C)

[[5 8]
 [6 9]]
[[ 3  2]
 [ 4 -1]]
[[47  2]
 [54  3]]


In [10]:
# Taking transpose
print(A)
B = A.T
print(B)

[[5 8]
 [6 9]]
[[5 6]
 [8 9]]


In [11]:
# Finding trace
print(A)
traceA = np.trace(A)
print(traceA)

[[5 8]
 [6 9]]
14


In [12]:
# Finding Matrix Determinant
A = np.array([[5,8],[6,9]])
print(A)
detA = np.linalg.det(A)
print(detA)

[[5 8]
 [6 9]]
-2.9999999999999982


In [13]:
# Matrix Inverse
print(A)
B = np.linalg.inv(A)
print(B)

[[5 8]
 [6 9]]
[[-3.          2.66666667]
 [ 2.         -1.66666667]]


An **identity matrix** of order 3 can be created as follows:

In [14]:
I3 = np.eye(3)
print(I3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


To create a 2x3 matrix of random numbers drawn from a normal distribution with mean 0 and variance 1, we use:

In [15]:
weights = np.random.randn(2,3)
print(weights)

[[ 0.19936222  2.25793337  1.85678371]
 [-0.15851752  0.71994685 -0.30182589]]


A 3x3 **diagonal matrix** with (1, 5, 1) along its principal diagonal can be constructed as follows:

In [16]:
A = np.diag((1, 5, 1))
print(A)

[[1 0 0]
 [0 5 0]
 [0 0 1]]


To create a 1x3 matrix of **ones**, we can do as follows:

In [17]:
print(np.ones((1,3)))

[[1. 1. 1.]]


### Task 1
Enter the matrix $\mathbf{A}=\begin{bmatrix}1 & 2 & 4 & 5 \\ 0 & 1 & 5 & -2 \\ 2 & -4 & 3 & 9 \end{bmatrix}$ in Python.<br>
Display the following: <br>
(a)  the size of the matrix $\mathbf{A}$ <br>
(b)  $a_{23}$, $a_{32}$ and $a_{34}$ <br>
(c)  row 1 and column 4 of $\mathbf{A}$

In [18]:
A = np.array([[1, 2, 4, 5], [0, 1, 5, -2], [2, -4, 3, 9]])
print("A = {}".format(A))

A = [[ 1  2  4  5]
 [ 0  1  5 -2]
 [ 2 -4  3  9]]


In [22]:
print("The size of matrix A is {} x {}".format(A.shape[0], A.shape[1]))

The size of matrix A is 3 x 4


In [20]:
print("𝑎23 -> {} \n𝑎32 -> {} \n𝑎34 -> {}".format(A[1,2], A[2,1], A[2,3]))

𝑎23 -> 5 
𝑎32 -> -4 
𝑎34 -> 9


In [29]:
print("Row 1:\n{} \nColumn 4:\n{}".format(A[0], A[:,[3]]))

Row 1:
[1 2 4 5] 
Column 4:
[[ 5]
 [-2]
 [ 9]]


### Task 2###
Enter the following matrices in Python. <br>
$\mathbf{A}=\begin{bmatrix}7 & -3 \\ 2 & 1 \\ 9 & -6 \\ -3 & 2 \end{bmatrix} , 
\mathbf{B}=\begin{bmatrix}2 \\ 5 \end{bmatrix} , 
\mathbf{C}=\begin{bmatrix}5 & 1 & -8 & 4 \\ 2 & 7 & -3 & 5\end{bmatrix}$ <br>
Compute each of the following expression if possible. <br>
(a) $\mathbf{AC}$ <br>
(b) $\mathbf{AB}$ <br>
(c) $\mathbf{A} + \mathbf{C}^T$ <br>
(d) $\mathbf{BA}$ <br>
(e) $\mathbf{AA}^T + \mathbf{C}^T\mathbf{C}$ <br>
(f) $\mathbf{A} + 2\mathbf{C}^T$

In [39]:
task2_A = np.array([[7, -3], [2, 1], [9, -6], [-3, 2]])
task2_B = np.array([[2], [5]])
task2_C = np.array([[5, 1, -8, 4], [2, 7, -3, 5]])
print("Matrix A:\n{}\n\nMatrix B:\n{}\n\nMatrix C:\n{}".format(task2_A, task2_B, task2_C))

Matrix A:
[[ 7 -3]
 [ 2  1]
 [ 9 -6]
 [-3  2]]

Matrix B:
[[2]
 [5]]

Matrix C:
[[ 5  1 -8  4]
 [ 2  7 -3  5]]


In [37]:
# (a)  𝐀𝐂 
task2_A.dot(task2_C)

array([[ 29, -14, -47,  13],
       [ 12,   9, -19,  13],
       [ 33, -33, -54,   6],
       [-11,  11,  18,  -2]])

In [40]:
# (b)  𝐀𝐁 
task2_A.dot(task2_B)

array([[ -1],
       [  9],
       [-12],
       [  4]])

In [42]:
# (c)  𝐀+𝐂𝑇 
task2_A + task2_C.T

array([[12, -1],
       [ 3,  8],
       [ 1, -9],
       [ 1,  7]])

In [43]:
# (d)  𝐁𝐀
task2_B.dot(task2_A)

ValueError: shapes (2,1) and (4,2) not aligned: 1 (dim 1) != 4 (dim 0)

In [48]:
# (e)  𝐀𝐀𝑇+𝐂𝑇𝐂 
task2_A.dot(task2_A.T) + task2_C.T.dot(task2_C)

array([[ 87,  30,  35,   3],
       [ 30,  55, -17,  35],
       [ 35, -17, 190, -86],
       [  3,  35, -86,  54]])

In [45]:
# (f)  𝐀+2𝐂𝑇
task2_A + 2*(task2_C.T)

array([[ 17,   1],
       [  4,  15],
       [ -7, -12],
       [  5,  12]])

### Task 3###
Determine if each of the following matrices is singular.<br>
(a) $\mathbf{A}=\begin{bmatrix}1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix}$ <br><br>
(b) $\mathbf{A}=\begin{bmatrix}0 & 1 & 3 & 4 \\ -2 & 1 & 2 & 1 \\ 2 & 0 & 1 & 0 \\ 0 & 8 & 3 & 1 \end{bmatrix}$ <br>

In [49]:
task3_Aa = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
task3_Ab = np.array([[0, 1, 3, 4], 
                     [-2, 1, 2, 1], 
                     [2, 0, 1, 0], 
                     [0, 8, 3, 1]])

print("Matrix A(a):\n{}\n\nMatrix A(b):\n{}".format(task3_Aa, task3_Ab))

Matrix A(a):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix A(b):
[[ 0  1  3  4]
 [-2  1  2  1]
 [ 2  0  1  0]
 [ 0  8  3  1]]


In [52]:
det3Aa = np.linalg.det(task3_Aa)
det3Ab = np.linalg.det(task3_Ab)

print("(a) Matrix A is not singular because |A| = {}".format(det3Aa))
print("(b) Matrix A is not singular because |A| = {}".format(det3Ab))

(a) Matrix A is not singular because |A| = -9.51619735392994e-16
(b) Matrix A is not singular because |A| = -126.0


### Task 4###
Find the inverse of each matrix.<br>
(a) $\mathbf{A}=\begin{bmatrix}2 & 1 \\ 3 & 5 \end{bmatrix}$ <br><br>
(b) $\mathbf{A}=\begin{bmatrix}1 & 1 & 2 \\ 2 & 1 & 1 \\ 1 & 2 & 1 \end{bmatrix}$

In [53]:
task4_Aa = np.array([[2, 1], [3, 5]])
task4_Ab = np.array([[1, 1, 2], [2, 1, 1], [1, 2, 1]])

print("Matrix A(a):\n{}\n\nMatrix A(b):\n{}".format(task4_Aa, task4_Ab))

Matrix A(a):
[[2 1]
 [3 5]]

Matrix A(b):
[[1 1 2]
 [2 1 1]
 [1 2 1]]


In [60]:
# (a)
inv_4Aa = np.linalg.inv(task4_Aa)
print("(a) Inverse of matrix A is \n{}".format(inv_4Aa))

(a) Inverse of matrix A is 
[[ 0.71428571 -0.14285714]
 [-0.42857143  0.28571429]]


In [61]:
# (b)
inv_4Ab = np.linalg.inv(task4_Ab)
print("(b) Inverse of matrix A is \n{}".format(inv_4Ab))

(b) Inverse of matrix A is 
[[-0.25  0.75 -0.25]
 [-0.25 -0.25  0.75]
 [ 0.75 -0.25 -0.25]]


### Task 5###
Determine the norm of each of the following vectors.<br>
(a) $\mathbf{v}_1=\begin{bmatrix}2 \\ -1 \\ 1 \end{bmatrix}$ <br><br>
(b) $\mathbf{v}_2=\begin{bmatrix}4 \\ 0 \\ 3 \\ -1 \end{bmatrix}$ <br><br>
(c) $\mathbf{v}_3=\begin{bmatrix}1 \\ 0 \\ 2 \\ 2 \\ 3 \end{bmatrix}$

In [67]:
task5_v1 = np.array([[2], [-1], [1]])
task5_v2 = np.array([[4], [0], [3], [-1]])
task5_v3 = np.array([[1], [0], [2], [2], [3]])

print("Vector v1:\n{} \n \nVector v2:\n{} \n \nVector v3:\n{}".format(task5_v1, task5_v2, task5_v3))

Vector v1:
[[ 2]
 [-1]
 [ 1]] 
 
Vector v2:
[[ 4]
 [ 0]
 [ 3]
 [-1]] 
 
Vector v3:
[[1]
 [0]
 [2]
 [2]
 [3]]


In [69]:
# (a)
norm_v1 = np.linalg.norm(task5_v1)
print("The norm of vector v1 is {}".format(norm_v1))

2.449489742783178

In [70]:
# (b)
norm_v2 = np.linalg.norm(task5_v2)
print("The norm of vector v2 is {}".format(norm_v2))

The norm of vector v2 is 5.0990195135927845


In [71]:
# (c)
norm_v3 = np.linalg.norm(task5_v3)
print("The norm of vector v3 is {}".format(norm_v3))

The norm of vector v3 is 4.242640687119285
