In [1]:
import numpy as np
print("numpy version: {}".format(np.__version__))

numpy version: 1.18.1


In [3]:
D = np.array([[1, 0, -1],
              [1, -3, 0],
              [-2, 2, 5]
             ])
np.linalg.det(D)

-11.000000000000002

In [5]:
C = np.array([[1, 0, -1],
              [1, -3, 0],
              [-2, 2, 5]
             ])
np.linalg.det(C)

-11.000000000000002

## Steps to determine the determinant of matrices
1. Make the array: *A = np.array([[1, 2], [3, 4]])*
2. Find the determinant: *detA = np.linalg.det(A)*

### Example 

In [17]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [16]:
detA = np.linalg.det(A)
detA

-2.0000000000000004

### Tutorial 1 

#### Problem 2(c) 

In [18]:
two_c = np.array([[1, 1, 1], [0, 1, 0], [1, 2, 1]])
two_c

array([[1, 1, 1],
       [0, 1, 0],
       [1, 2, 1]])

In [21]:
det_two_c = np.linalg.det(two_c)
det_two_c

0.0

#### Problem 2(d) 

In [22]:
two_d = np.array([[1, -1, 0], [2, 3, 0], [0, 2, 1]])
two_d

array([[ 1, -1,  0],
       [ 2,  3,  0],
       [ 0,  2,  1]])

In [3]:
a = np.array([[0, 0, 1], [0, 1, 0], [1, 0, 0]])
a

array([[0, 0, 1],
       [0, 1, 0],
       [1, 0, 0]])

In [4]:
np.linalg.det(a)

-1.0

In [23]:
det_two_d = np.linalg.det(two_d)
det_two_d

5.000000000000001

#### Problem 7(a) 

In [29]:
sev_ai = np.array([[1, 0], [3, 2]])
sev_ai

array([[1, 0],
       [3, 2]])

In [30]:
sev_aii = np.array([[5, 4], [6, 7]])
sev_aii

array([[5, 4],
       [6, 7]])

In [32]:
sev_a = np.matmul(sev_ai, sev_aii)
sev_a

array([[ 5,  4],
       [27, 26]])

In [15]:
sev_bi = np.array([[1, 0], [3, 2]])
sev_bi

array([[1, 0],
       [3, 2]])

In [16]:
sev_bii = np.array([[5, 4, 8], [6, 7, 9]])
sev_bii

array([[5, 4, 8],
       [6, 7, 9]])

In [18]:
sev_b = sev_bi.dot(sev_bii)
print(sev_b)

[[ 5  4  8]
 [27 26 42]]


#### Problem 10

In [44]:
Q = np.array([[5/13, 12/13], [-12/13, 5/13]])
Q

array([[ 0.38461538,  0.92307692],
       [-0.92307692,  0.38461538]])

In [45]:
Q.T.dot(Q)

array([[ 1.0000000e+00, -2.6277468e-18],
       [-2.6277468e-18,  1.0000000e+00]])

In [46]:
np.around(Q.T.dot(Q))

array([[ 1., -0.],
       [-0.,  1.]])